### ISSUE TITLE
Running start.sh -d outputs error in 1make-dbusers.sh regarding failed creation of postgres role

### ISSUE THREAD

**Issue by nam20485** [hackoregon/backend-examplar-2018#38] opened 2018-04-24 02:28 UTC
1. Copy disaster.backup into Backups/
2. Set .env variables to:
DEVELOPMENT_POSTGRES_USER=postgres
DEVELOPMENT_POSTGRES_NAME=disaster
DEVELOPMENT_DATABASE_OWNER=postgres
3. Run create-project.sh -d and start.sh -d

Error message is displayed in output:

'/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/1make-dbusers.sh
db_development_1   | Creating database user postgres
db_development_1   | ERROR:  role "postgres" already exists
db_development_1   | STATEMENT:  CREATE ROLE postgres NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION;
db_development_1   | createuser: creation of new role failed: ERROR:  role "postgres" already exists'

**Comment by znmeb** [comment] 2018-04-24 02:36
Duplicate of #37

**Closed by znmeb** 2018-04-24 02:36 UTC
